package index

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

type impactFixture struct {
	root     string
	service  string
	consumer string
	base     string
	cfg      IndexConfig
}

func TestImpactSinceReportsBodyChangesDeletedSymbolsAndStructuralBlastRadius(t *testing.T) {
	fixture := newImpactFixture(t)
	writeImpactFile(t, fixture.service, "policy/policy.go", `package policy

type Authorizer interface { Decide() bool }
type Engine struct{}
func (e *Engine) Decide() bool { return true }
func Call(e *Engine) bool { return e.Decide() }
`)
	writeImpactFile(t, fixture.service, "policy/config.go", `package policy
type Config struct { Mode string; Strict bool }
`)
	writeImpactFile(t, fixture.service, "api/service.pb.go", `// Code generated by test. DO NOT EDIT.
package api
type ExampleServiceServer interface { Get(); Put() }
`)
	writeImpactFile(t, fixture.service, "policy/new.go", "package policy\nfunc Added() {}\n")
	if err := os.Remove(filepath.Join(fixture.service, "policy", "obsolete.go")); err != nil {
		t.Fatal(err)
	}

	idx, err := BuildIndex(fixture.cfg)
	if err != nil {
		t.Fatal(err)
	}
	holder := NewHolder(idx, fixture.cfg)
	report, err := holder.ImpactSince("service", fixture.base)
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range []struct {
		name   string
		change SymbolChangeKind
	}{
		{"Engine.Decide", SymbolModified},
		{"Config", SymbolModified},
		{"ExampleServiceServer", SymbolModified},
		{"Added", SymbolAdded},
		{"Removed", SymbolDeleted},
	} {
		if !impactHasChange(report.ChangedSymbols, expected.name, expected.change) {
			t.Errorf("missing %s %s in %#v", expected.name, expected.change, report.ChangedSymbols)
		}
	}
	if !impactHasSymbol(report.AffectedSymbols, "Call") || !impactHasSymbol(report.AffectedSymbols, "Use") {
		t.Errorf("callers absent from affected symbols: %#v", report.AffectedSymbols)
	}
	if !impactHasSymbol(report.Interfaces, "Authorizer") {
		t.Errorf("implicit interface absent: %#v", report.Interfaces)
	}
	if !impactHasSymbol(report.ConfigStructs, "Config") {
		t.Errorf("config struct absent: %#v", report.ConfigStructs)
	}
	if !impactHasSymbol(report.Services, "ExampleServiceServer") {
		t.Errorf("service absent: %#v", report.Services)
	}
	if !impactHasSymbol(report.CandidateTests, "TestDefaultDeny") {
		t.Errorf("candidate test absent: %#v", report.CandidateTests)
	}
	if !includesImpactString(report.AffectedRepositories, "consumer") {
		t.Errorf("cross-repository impact absent: %v", report.AffectedRepositories)
	}
	if report.Snapshot.Repository != "service" || report.Snapshot.BaseCommit != fixture.base ||
		report.Snapshot.HeadCommit == "" || report.Snapshot.TrackedDiffDigest == "" ||
		report.Snapshot.UntrackedManifestDigest == "" || report.Snapshot.WorktreeDigest == "" ||
		report.Snapshot.Generation != 1 || report.Snapshot.ToolchainIdentity == "" || report.ImpactDigest == "" {
		t.Fatalf("snapshot or digest incomplete: %#v", report)
	}
	if report.ImpactDigest != ImpactDigest(report) {
		t.Fatalf("impact digest is not reproducible: %#v", report)
	}
}

func TestImpactSinceRejectsSourceChangedAfterPublishedIndex(t *testing.T) {
	fixture := newImpactFixture(t)
	idx, err := BuildIndex(fixture.cfg)
	if err != nil {
		t.Fatal(err)
	}
	holder := NewHolder(idx, fixture.cfg)
	writeImpactFile(t, fixture.service, "policy/policy.go", `package policy
type Authorizer interface { Decide() bool }
type Engine struct{}
func (e *Engine) Decide() bool { return true }
func Call(e *Engine) bool { return e.Decide() }
`)
	if _, err := holder.ImpactSince("service", fixture.base); err == nil || !strings.Contains(err.Error(), "reindex") {
		t.Fatalf("stale index error = %v", err)
	}
}

func TestImpactDigestMatchesIntentContract(t *testing.T) {
	report := ImpactReport{
		Snapshot: SourceSnapshot{
			Repository: "service", BaseCommit: "base", HeadCommit: "head", Branch: "main",
			TrackedDiffDigest: "tracked", UntrackedManifestDigest: "untracked",
			WorktreeDigest: "worktree", Generation: 9, ToolchainIdentity: "go1.test test/arch",
		},
		ChangedFiles: []FileChange{
			{Path: "z.go", Status: "M"}, {Path: "a.go", OldPath: "old.go", Status: "R"},
		},
		ChangedSymbols: []SymbolChange{
			{Symbol: SymbolIdentity{Repository: "service", Package: "example.test/policy", Name: "Engine.Decide", Kind: SymbolMethod}, Change: SymbolModified},
			{Symbol: SymbolIdentity{Repository: "service", Package: "example.test/policy", Name: "Config", Kind: SymbolType}, Change: SymbolAdded},
		},
		AffectedSymbols: []SymbolIdentity{
			{Repository: "service", Package: "example.test/release", Name: "Enforcer.Release", Kind: SymbolMethod},
		},
		Interfaces:    []SymbolIdentity{},
		ConfigStructs: []SymbolIdentity{{Repository: "service", Package: "example.test/policy", Name: "Config", Kind: SymbolType}},
		Services:      []SymbolIdentity{},
		CandidateTests: []SymbolIdentity{
			{Repository: "service", Package: "example.test/policy", Name: "TestDefaultDeny", Kind: SymbolFunc},
		},
		AffectedRepositories: []string{"worker", "service"},
	}
	const expected = "d40868eb16519e75f44c3d104530288297717cb777cb095d7d8dc07fa2a673d8"
	if got := ImpactDigest(report); got != expected {
		t.Fatalf("impact digest contract = %s", got)
	}
}

func TestImpactSinceUsesConfiguredModuleRelativePathsInMonorepo(t *testing.T) {
	root := t.TempDir()
	impactGit(t, root, "init", "-q")
	impactGit(t, root, "config", "user.name", "Nested Module Test")
	impactGit(t, root, "config", "user.email", "nested@example.invalid")
	moduleRoot := filepath.Join(root, "services", "policy")
	writeImpactFile(t, root, "services/policy/go.mod", "module example.local/policy\n\ngo 1.24\n")
	writeImpactFile(t, root, "services/policy/policy.go", "package policy\nfunc Decide() bool { return false }\n")
	writeImpactFile(t, root, "unrelated/other.txt", "unchanged\n")
	impactGit(t, root, "add", ".")
	impactGit(t, root, "commit", "-q", "-m", "base")
	base := impactGit(t, root, "rev-parse", "HEAD")
	writeImpactFile(t, root, "services/policy/policy.go", "package policy\nfunc Decide() bool { return true }\n")
	cfg := IndexConfig{Repos: []RepoConfig{{Name: "policy", Path: moduleRoot}}}
	holder, err := BuildHolder(cfg)
	if err != nil {
		t.Fatal(err)
	}
	report, err := holder.ImpactSince("policy", base)
	if err != nil {
		t.Fatalf("impact since: %v", err)
	}
	if len(report.ChangedFiles) != 1 || report.ChangedFiles[0].Path != "policy.go" ||
		!impactHasChange(report.ChangedSymbols, "Decide", SymbolModified) {
		t.Fatalf("nested module impact = %#v", report)
	}
}

func newImpactFixture(t *testing.T) impactFixture {
	t.Helper()
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git is required")
	}
	root := t.TempDir()
	service := filepath.Join(root, "service")
	consumer := filepath.Join(root, "consumer")
	for _, repo := range []string{service, consumer} {
		if err := os.MkdirAll(repo, 0o755); err != nil {
			t.Fatal(err)
		}
		impactGit(t, repo, "init", "-q")
		impactGit(t, repo, "config", "user.name", "Impact Test")
		impactGit(t, repo, "config", "user.email", "impact@example.invalid")
		impactGit(t, repo, "config", "core.autocrlf", "false")
	}
	writeImpactFile(t, service, "go.mod", "module example.local/service\n\ngo 1.24\n")
	writeImpactFile(t, service, "policy/policy.go", `package policy

type Authorizer interface { Decide() bool }
type Engine struct{}
func (e *Engine) Decide() bool { return false }
func Call(e *Engine) bool { return e.Decide() }
`)
	writeImpactFile(t, service, "policy/config.go", "package policy\ntype Config struct { Mode string }\n")
	writeImpactFile(t, service, "policy/obsolete.go", "package policy\nfunc Removed() {}\n")
	writeImpactFile(t, service, "policy/policy_test.go", "package policy\nimport \"testing\"\nfunc TestDefaultDeny(t *testing.T) { _ = (&Engine{}).Decide() }\n")
	writeImpactFile(t, service, "api/service.pb.go", `// Code generated by test. DO NOT EDIT.
package api
type ExampleServiceServer interface { Get() }
`)
	impactGit(t, service, "add", ".")
	impactGit(t, service, "commit", "-q", "-m", "base")
	base := impactGit(t, service, "rev-parse", "HEAD")

	writeImpactFile(t, consumer, "go.mod", "module example.local/consumer\n\ngo 1.24\n\nrequire example.local/service v0.0.0\nreplace example.local/service => ../service\n")
	writeImpactFile(t, consumer, "consumer.go", `package consumer
import "example.local/service/policy"
func Use(engine *policy.Engine) bool { return engine.Decide() }
`)
	impactGit(t, consumer, "add", ".")
	impactGit(t, consumer, "commit", "-q", "-m", "base")

	return impactFixture{
		root: root, service: service, consumer: consumer, base: base,
		cfg: IndexConfig{Repos: []RepoConfig{
			{Name: "service", Path: service, IncludeTests: true, TypedMethodReferences: true},
			{Name: "consumer", Path: consumer, IncludeTests: true, TypedMethodReferences: true},
		}},
	}
}

func writeImpactFile(t *testing.T, root, relative, contents string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(relative))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatal(err)
	}
}

func impactGit(t *testing.T, directory string, args ...string) string {
	t.Helper()
	command := exec.Command("git", args...)
	command.Dir = directory
	command.Env = append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1")
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, output)
	}
	return strings.TrimSpace(string(output))
}

func impactHasChange(changes []SymbolChange, name string, change SymbolChangeKind) bool {
	for _, candidate := range changes {
		if candidate.Symbol.Name == name && candidate.Change == change {
			return true
		}
	}
	return false
}

func impactHasSymbol(symbols []SymbolIdentity, name string) bool {
	for _, symbol := range symbols {
		if symbol.Name == name {
			return true
		}
	}
	return false
}

func includesImpactString(values []string, wanted string) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}
	return false
}
