// Code generated by protoc-gen-go. DO NOT EDIT.

package sample

// MessageType is a generated enum for message types.
type MessageType int32

const (
	// MessageType_UNKNOWN is the default value.
	MessageType_UNKNOWN MessageType = 0
	// MessageType_REQUEST is a request message.
	MessageType_REQUEST MessageType = 1
)

// ProtoMessage is a generated message struct.
type ProtoMessage struct {
	Id   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type MessageType `protobuf:"varint,2,opt,name=type,proto3,enum=sample.MessageType" json:"type,omitempty"`
}

// GetId returns the Id field.
func (m *ProtoMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// GetType returns the Type field.
func (m *ProtoMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN
}
