// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sample

import "context"

// GreeterServiceServer is the server API for GreeterService service.
type GreeterServiceServer interface {
	// SayHello sends a greeting.
	SayHello(context.Context, *ProtoMessage) (*ProtoMessage, error)
	mustEmbedUnimplementedGreeterServiceServer()
}

// UnsafeGreeterServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeGreeterServiceServer interface {
	mustEmbedUnimplementedGreeterServiceServer()
}
